apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: echoer-deployment1
spec:
  selector:
    matchLabels:
      app: echoer
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: echoer
        version: v1
    spec:
      containers:
      - name: echoermain
        image: jakkaj/basic-env-write:1 # Update the version of nginx from 1.7.9 to 1.8
        ports:
        - containerPort: 8001
        env:
        - name: ECHOENV
          value: "Hello from version 1"
      nodeSelector:
        beta.kubernetes.io/os: linux
